### ISSUE TITLE
Linux Pip SSL problem

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#10]
Tried using Alexandria Trail + FMXLinux Trial to build on Ubuntu 22.04 (any project that uses Pip should have the same issue)

`WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
`
More detailed log...

[lartis.log](https://github.com/Embarcadero/PythonEnviroments/files/9389465/lartis.log)

**Comment by lmbelo** [comment]
This is nothing regarding the DelphiFMX library. This is regarding the Python version you're installing. You're using a non-ssl compiled version.

**Comment by peardox** [comment]
I'm supposed to be using whatever's in PythonEnvironments/python - so this one... python3-linux-3.9.12-x86_64.zip

**Comment by lmbelo** [comment]
Have you tried to install SLL with APT?

**Comment by peardox** [comment]
Got libssl-dev and NOT any APT pip (just default python 3.10 which is no good for project)

**Comment by lmbelo** [comment]
Install the libessl and you're good to use the Python embeddable that we are sharing on.

**Comment by peardox** [comment]
This is actually just pre-work for when I get my SteamDeck in a few months BTW

**Comment by lmbelo** [comment]
I too want a SteamDeack xP

**Comment by peardox** [comment]
Should get mine about October. They've got an AMD RDNA2 GPU in them that should theoretically work with PyTorch Linux - at least I hope so. I like the idea of launching my project on Steam at some point

Not been able to test on Linux as Laptop has NVidia GPU so the also-present AMD on-chip RDNA is ignored :(

**Comment by lmbelo** [comment]
Ohh, it looks very cool. Share your thoughts and maybe a video when you get it.

**Comment by peardox** [comment]
I already plan to - video + all. I should (probably) have the first YouTube video on Machine Learning with a Steam Deck (and a Trial copy of Delphi...) :)

**Comment by lmbelo** [comment]
> I already plan to - video + all. I should (probably) have the first YouTube video on Machine Learning with a Steam Deck (and a Trial copy of Delphi...) :)

I'd love to watch it. Let me know if you need help.

**Comment by peardox** [comment]
Fixed
