### ISSUE TITLE
GetPip is currently broken

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#21]
With a GetPIP component on the form compilation results in the following error

> [dcc64 Error] E1026 File not found: '..\..\resources\getpipscript.res'

Removing the GetPIP (fairly obvioously) resolves the issue BUT this means that dev created GetPIP will also fail

I have changed my PYTHONENVIRONMENTDIR (new Delphi, fresh build of all components)

**Comment by lmbelo** [comment]
You must compile all components instead of only linking to its sources. All the .res files are build at projects compile time.

**Comment by peardox** [comment]
All components are installed using the following steps

1) Double-click on [repo].groupproj
2) Build All (Win32 Release)
3) Install Components (Win32 Release)
4) Build All (Win32 Debug)
5) Build All (Win64 Release)
6) Build All (Win64 Debug)
7) Open Tools -> Options -> Language -> Delphi -> Library
8) Add new Library Path(s) (lib/Win64/release)
9) Add new Debug DCU Path(s) (lib/Win64/debug)
10) Add new Library Path(s) (lib/Win32/release)
11) Add new Debug DCU Path(s) (lib/Win32/debug)
12) Close Delphi without saving project (so it opens as Win32 if you need to do it again)

This process is repeated for each of the five repos = 60 steps in total - see, needs instructions :)

**Comment by lmbelo** [comment]
Presumably you got it working out, right?

**Comment by peardox** [comment]
But with the above steps which should be those required for proper installation GetPIP  throws the above error

Maybe adding the source directory will resolve the issue? Not a very elegant solution though...

**Comment by lmbelo** [comment]
As you need to set a path to the lib folder, you definitely need to set a path to the resource folder. How would the linker find the respective .res file to embed it to the executable file?

**Comment by peardox** [comment]
Wasn't sure if it was needed or not

Which entry Browsing Path I guess?

![image](https://user-images.githubusercontent.com/1549219/196006405-6847a531-88e3-465c-b2a7-9262d47d8bb7.png)

**Comment by lmbelo** [comment]
Library path.

**Comment by peardox** [comment]
Doesn't your Enable Python IDE thing do this too?

i.e. either add e.g. [D:\Delphi\Components\PythonEnviroments\src\AddOn] to Library or select Enable Python from the project menu?

**Comment by peardox** [comment]
Works again nicely now - thx
