### ISSUE TITLE
Branch pyupgrade report

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#24]
Works great so far (yet to give it the harder tests)

Windows x64 runs as normal with newer Python 3.9.15 (only version tested)

Linux x64 runs great on the build box as does my PR for GetPIP - need to see what other Linux distros think of it, got Arch x64 x2 - One a laptop with latest and one older one on Steam Deck. Also want to try running in a clean VM with Ubu 20.04 + 22.04 (build box is 22.04)

Linux images...

![image](https://user-images.githubusercontent.com/1549219/196013620-75e99832-c932-4a07-a434-774912e9fdbc.png)
Note  this is the FIRST time this has worked without me having to hack around with the system to firnd missing libs

The next image is a re-run - rather similar (expected) but note the PIP version is now 22.3

![image](https://user-images.githubusercontent.com/1549219/196013650-8af275c3-7980-4139-b263-fbfee994cdb1.png)

I'll try other Distros in the AM (02:30 here - been at it all day, rest time)

Looks like a good candidate for moving to main to me

**Comment by peardox** [comment]
Oh - just noticed a Python error - this is NOT PythonEnvironment in any way - that's 'cos the thing's running on a really old GPU that doesn't support some things

**Comment by peardox** [comment]
Well, bed in a bit...

Steam Deck - Delphi issue probably fixed by using 22.04 as a buildbox
![image](https://user-images.githubusercontent.com/1549219/196014563-72c81d86-44fe-4a20-bb1b-8a3503584a4d.png)

It seems to be running on the Arch box but that things dead old so waiting for results - newer OS must have the required GLIBC

**Comment by peardox** [comment]
Slow machine eventually finished
![image](https://user-images.githubusercontent.com/1549219/196014745-b9931422-f303-4272-9267-add1b634e0f2.png)

This is the same executable on an Arch Laptop (which will become a Ubu 20.04 Laptop in some hours) - Static seems to be working really well then

**Comment by lmbelo** [comment]
https://docwiki.embarcadero.com/RADStudio/Sydney/en/Linux_Application_Development

**Comment by peardox** [comment]
Yeah, read all that months ago. Looked into Flatpak as a workaround - whole different set of problems - wan't a makefile...

Ubuntu 20.04 looks like it will work as a base build target (can't use Arch - the proper target - not recognosed by Delphi) for Steam Deck now Python is static - about to find out.

**Comment by peardox** [comment]
Yaayyy! Added 20.04 to buildbox (now dual Linux boot) and compiled up 20.04 version of SimplePython test then copied just the executable to Steam Deck and...

![image](https://user-images.githubusercontent.com/1549219/196046906-470851b7-41d2-4a0f-a48e-5559b8570788.png)

Good result!

**Comment by peardox** [comment]
Rats - Lartis fails owing to bzip2 compatability

Checking StackOverflow this appears to be a common issue

This can, however, be a misleading report as it could be another dependancy of _bz2 causing a bad error report

**Comment by peardox** [comment]
This looks helpful
https://github.com/indygreg/python-build-standalone

**Comment by lmbelo** [comment]
I too want a Steam Deck.

**Comment by lmbelo** [comment]
> Rats - Lartis fails owing to bzip2 compatability
> 
> Checking StackOverflow this appears to be a common issue
> 
> This can, however, be a misleading report as it could be another dependancy of _bz2 causing a bad error report

Share your error then.

**Comment by peardox** [comment]
> I too want a Steam Deck.
I was lucky, the government gave some people without a "job" 650 GBP in two parts. That was enough to get the mid-range Steam Deck with a Dock and some other stuff. They are, however, not really up to running AI to be honest as the GPU is AMD (I'd hoped ROCm yould work - it doesn't).

> Share your error then.
```
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/deck/.Lartis/pysrc/mlfuncts.py", line 11, in <module>
    from torchvision import datasets
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/site-packages/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import verify_str_arg
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/site-packages/torchvision/datasets/utils.py", line 1, in <module>
    import bz2
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
Import Exception in RunSystem
Class : EPyImportError
Error : ModuleNotFoundError: No module named '_bz2'
Value : No module named '_bz2'
Name : ModuleNotFoundError
RunSystem Completed

```

I _think_ that compiling the Python on an distro may help as the main Delphi worked fine on the deck - \i'll give it a go to see what happens.

**Comment by peardox** [comment]
Here's a slightly more specific error report by running the embedded manually

> (deck@steamdeck 3.9)$ ./py
Python 3.9.15 (main, Oct 15 2022, 19:07:07)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
import bz2 ### I typed this ###
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deck/.Lartis/python/3.9/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by peardox** [comment]
After some hacking around I got a version that sorta works

From Python buil;d docs

> At the end of the build you should see a success message, possibly followed by a list of extension modules that havenï¿½t been built because their dependencies were missin
>
>Python build finished successfully!
The necessary bits to build these optional modules were not found:
_bz2                  _dbm                  _gdbm
_lzma                 _sqlite3              _ssl
_tkinter              _uuid                 readline
zlib

And...

> sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev

So I did that and copied the missing _bz2.cpython-39-x86_64-linux-gnu.so to the deck's lib/python3.9 dir and it all worked fine again.

I have previously seen missing lzma related stuff when testing on Mac as well

**Comment by lmbelo** [comment]
bzip2 is included as dependency in our CI

https://github.com/lmbelo/python3-embeddable/blob/7c38c613ea39caf1948684ce73681438494c509e/python3-linux/Linux/build_deps.py#L41

**Comment by lmbelo** [comment]
I found the error. I'm fixing it.

**Comment by peardox** [comment]
Well, installing with the pyupgrade branch it errored as above - do I need a different branch?

**Comment by peardox** [comment]
Cool

**Comment by lmbelo** [comment]
Update it and retry.

**Comment by lmbelo** [comment]
I will remove TK from the macOS package, it will lean out the final zip file.

**Comment by peardox** [comment]
Updated and retried - perfect

May as well release it unless you need anything else checking

Possibly add Update GetPIP PR?

**Comment by peardox** [comment]
Python on Linux Steam Deck...
![image](https://user-images.githubusercontent.com/1549219/196296771-a19e8bdc-a4d2-4d97-85da-97e6e1067e4a.png)

**Comment by peardox** [comment]
Can you promote pyupgrade to main please - I just got proper 11.2 and I've just installed the version with broken Linux

Accepting the getpip upgrade property code would also help

**Comment by peardox** [comment]
I also note that Python 3.11 has just gone public release - definitely a good time to update this repo

**Comment by lmbelo** [comment]
@peardox new changes were just merged. I will release a new version as we get cp3.11 working.

**Comment by peardox** [comment]
@lmbelo What changed are there? There's no fixes list I can see.

I notice samples is new

**Comment by lmbelo** [comment]
Fix list will be displayed in new releases

**Comment by peardox** [comment]
Got a little weekly household stuff to do, will start a fresh test when that's done.

I've been playing with finding all Installed Components to improve my https://github.com/peardox/MakeP4DComponents (reading Registry - not ToolsApi)

It looks like the stuff I'm doing there might be good for a P4D Suite install useful as well as I'm identifying things that go wrong when installing

**Comment by peardox** [comment]
Closing this cos we're on a new branch
