### ISSUE TITLE
PyEnvironment.Embeddable.pas Broken

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#3]
Line 240 of ...
https://github.com/Embarcadero/PythonEnviroments/blob/main/src/Embeddable/PyEnvironment.Embeddable.pas

Is $ifdefed out for Windows

```
{$IFNDEF MSWINDOWS}
var
  LFiles: TArray<string>;
{$ENDIF}
begin
```

But is referenced on line 259 meaning it won't compile under Windows

(I was just trying a fresh install to write a guide)

**Comment by lmbelo** [comment]
@peardox nice catch. I will fix it. Thank you.
