### ISSUE TITLE
Won't compile Android

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#4]
On a fork comment out the ifndef for windows so it compiles and Android goes bad...

[DCC Fatal Error] PyEnvironment.Project.pas(1): F2039 Could not create output file '.\Android64\Release\PyEnvironment.Project.hpp'

That's a new one on me...

**Comment by lmbelo** [comment]
Ohhh, it might not be related to the project itself. Have you tried in a different project?

**Comment by peardox** [comment]
I'm trying to build the library so I can try out an Android buld

Library build is what's failing (10.4.2 CE)

**Comment by lmbelo** [comment]
I will try it and let you know what I figured out.

**Comment by peardox** [comment]
I've got a ChomeBook arriving in 10 mins or so - wanted to see if that would take at least a simple project :)

**Comment by lmbelo** [comment]
I also want to check it. I'll try to fix it (if I find the bug) and then you can try it on the ChromeBook.

**Comment by peardox** [comment]
The world's worst ChromeBook has just arrived :)

I wanted REALLY BAD - and that's exactly what 120 quid gets you :)

If this thing can run P4D anything can :)

**Comment by lmbelo** [comment]
Haaa I like it. 💪
