### ISSUE TITLE
[Enhancement] Add a sample showing how to install packages via PIP

### ISSUE THREAD

**Issue by Basti-Fantasti** [Embarcadero/PythonEnviroments#43]
When deploying a Python Embedded environment, pip is automatically installed.
It would be great to have a sample project which e.g. installs requests from pip just to show the process on how to use pip in the embedded environment

Ideal would also be a sample python script which calls the requests module from within the installed embedded environment

(If I can manage it on my own I will make a PR)

**Comment by HuguesDug** [comment]
Hello,

When I do this, it installs the requirement in my user app roaming folder and not in the embeded environment.

Any hint ?

I have struggled a while with this problem.

**Comment by lmbelo** [comment]
Hello, I will create and share a sample project installing PIP packages.
