### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by peardox** [Embarcadero/PythonEnviroments#6]
![image](https://user-images.githubusercontent.com/1549219/183542417-f661b4ec-530e-4418-9e1a-41dfdaeef1f3.png)

It's trying to check if a DIRECTORY exists called "C:\src\zzz\HelloCPU\Win64\Debug\python\3.9\python.exe"

**Comment by lmbelo** [comment]
Can you share the steps to reproduce?

**Comment by peardox** [comment]
My route was a little lengthy... Uninstall everything, Install Everything

This appears to be down to the newest version of python4delphi as I tried replacing PythonEnvironments with an earlier version and it still breaks

I'll go find myself and older python4delphi I guess - it was all working before I installed the new packages

Actually python4delphi didn't like building as Android either but I was in the middle of removing an underscore from cv2_ so skipped that issue (to look at later)

**Comment by peardox** [comment]
Found it

It broke when you fixed the {$ifndef MSWINDOWS} thing

I'm gonna patch mine for now - will show what's wrong in a PR soon

**Comment by peardox** [comment]
Fixed in PR#7
